
Para realizar este ejercicio usted puede usar Colab, ya que necesitará realizar muchas operaciones matriciales, como suma de matrices y multiplicación. El resto de la operaciones las puede realizar en papel.


## Introducción al Código de Codificación

Para codificar un mensaje, utilizaremos una correspondencia entre letras y números basada en el alfabeto:

Aquí tienes la tabla completa que asocia cada letra del alfabeto en mayúsculas con su código numérico del 1 al 26, más el espacio representado por 0.

### Tabla de correspondencia letra-código

| Letra   | Código |
|---------|--------|
| A       | 1      |
| B       | 2      |
| C       | 3      |
| D       | 4      |
| E       | 5      |
| F       | 6      |
| G       | 7      |
| H       | 8      |
| I       | 9      |
| J       | 10     |
| K       | 11     |
| L       | 12     |
| M       | 13     |
| N       | 14     |
| O       | 15     |
| P       | 16     |
| Q       | 17     |
| R       | 18     |
| S       | 19     |
| T       | 20     |
| U       | 21     |
| V       | 22     |
| W       | 23     |
| X       | 24     |
| Y       | 25     |
| Z       | 26     |
| Espacio | 0      |
**Ejemplo:**  
La palabra `"VIDAS"` se convierte en:

# Actividad computacional 3


Para realizar este ejercicio usted puede usar Colab, ya que necesitará realizar muchas operaciones matriciales, como suma de matrices y multiplicación. El resto de la operaciones las puede realizar en papel. Lea atentamente los ejemplos antes de realizar los ejercicios.


## Introducción al Código de Codificación

Para codificar un mensaje, utilizaremos una correspondencia entre letras y números basada en el alfabeto:

Aquí tienes la tabla completa que asocia cada letra del alfabeto en mayúsculas con su código numérico del 1 al 26, más el espacio representado por 0.

### Tabla de correspondencia letra-código

| Letra   | Código |
|---------|--------|
| A       | 1      |
| B       | 2      |
| C       | 3      |
| D       | 4      |
| E       | 5      |
| F       | 6      |
| G       | 7      |
| H       | 8      |
| I       | 9      |
| J       | 10     |
| K       | 11     |
| L       | 12     |
| M       | 13     |
| N       | 14     |
| O       | 15     |
| P       | 16     |
| Q       | 17     |
| R       | 18     |
| S       | 19     |
| T       | 20     |
| U       | 21     |
| V       | 22     |
| W       | 23     |
| X       | 24     |
| Y       | 25     |
| Z       | 26     |
| Espacio | 0      |

**Ejemplo:**  
La palabra `"VIDAS"` se convierte en:

$$
V = 22, \quad I = 9, \quad D = 4, \quad A = 1, \quad S = 19
$$

y se agrupa en vectores de dos en dos:

$$
v_1=\begin{bmatrix} 22 \\ 9 \\ 4 \end{bmatrix}, \quad v_2=\begin{bmatrix} 1 \\ 19 \\ 0 \end{bmatrix}.
$$
 Note que aqui para cifra la palabra se ha añadido un espacio al final para completar el bloque de dos. Así para codificar un mensaje, primero se convierte cada letra en su código numérico correspondiente y luego se agrupan en vectores de dos en dos. Si el mensaje tiene un número impar de letras, se añade un espacio (código 0) al final para completar el último bloque. Luego se utiliza una matriz de codificación para transformar estos vectores en nuevos vectores codificados.

## Matriz de Codificación
La matriz de codificación que utilizaremos es la siguiente:
$$
C = \begin{bmatrix} 3 & 2 &-1\\ 5 & 7&0\\1&0&1 \end{bmatrix}
$$

Luego de agrupar el mensaje en vectores de dos en dos, se multiplica cada vector por la matriz de codificación $C$ para obtener los vectores codificados.

Así, los vectores codificados son:


$$
C\cdot v_1 =  \begin{bmatrix} 80 \\ 173 \\ 26 \end{bmatrix}\ \text{ y }\ \ C\cdot v_2 =  \begin{bmatrix} 22 \\ 16 \\ 1 \end{bmatrix}
$$ 

de esta forma podemos escribir el mensaje codificado como la secuencia de números:

$$\{80, 173, 26, 22, 16, 1\}$$

## Descifrado del Mensaje

Para descifrar el mensaje, necesitamos la matriz inversa de la matriz de codificación $C$. La matriz inversa $C^{-1}$ es:
$$
C^{-1} = \begin{bmatrix} 7/11 & -2/11 & 1/11 \\ -5/11 & 3/11 & 0 \\ 5/11 & 1/11 & -6/11 \end{bmatrix}   
$$
Luego, para descifrar cada vector codificado, multiplicamos el vector codificado por la matriz inversa $C^{-1}$.
Así, para los vectores codificados obtenidos anteriormente, tenemos:    
$$
C^{-1}\cdot \begin{bmatrix} 80 \\ 173 \\ 26 \end{bmatrix} = \begin{bmatrix} 22 \\ 9 \\ 4 \end{bmatrix} = v_1
$$
y
$$
C^{-1}\cdot \begin{bmatrix} 22 \\ 16 \\ 1 \end{bmatrix} = \begin{bmatrix} 1 \\ 19 \\ 0 \end{bmatrix} = v_2
$$
De esta forma, recuperamos los vectores originales $v_1$ y $v_2$, que corresponden a los códigos numéricos de las letras del mensaje original. Finalmente, convertimos estos códigos numéricos de vuelta a letras utilizando la tabla de correspondencia inicial para obtener el mensaje descifrado.
-La palabra `"VIDAS"` se convierte en:  
$$
V = 22, \quad I = 9, \quad D = 4, \quad A = 1, \quad S = 19
$$     



**Nota** Recuerda si una matriz es diagonalizable, y si tenemos sus autovalores y vectores propios, podemos reconstruir la matriz original usando la descomposición espectral.

**Ejemplo**

Para el caso de una matriz cuadrada $A$ de tamaño $2\times 2$, si conocemos sus autovalores $\lambda_1$ y $\lambda_2$, y sus vectores propios correspondientes $v_1$ y $v_2$, podemos expresar la matriz $A$ como:
$$A = P\Lambda P^{-1}$$
donde $P$ es la matriz cuyas columnas son los vectores propios $v_1$ y $v_2$, y $\Lambda$ es la matriz diagonal cuyos elementos diagonales son los autovalores $\lambda_1$ y $\lambda_2$. Así un ejemplo numérico sería:


$$
A = \begin{bmatrix} 0 & 1 \\ 1 & 0\end{bmatrix},
$$
entonces los valores propios de $A$ son 

$\lambda_1 = 1$ asociado al vector propio
$v_1 = \begin{bmatrix} 1 \\ 1\end{bmatrix}$    y    $\lambda_2 = -1$ asociado al vector propio $v_2 = \begin{bmatrix} 1 \\ -1\end{bmatrix}$. 

De esta forma, tenemos que la matriz

$$
P = \begin{bmatrix} 1 & 1 \\ 1 & -1\end{bmatrix},
\ \
\Lambda = \begin{bmatrix} 1 & 0 \\ 0 & -1\end{bmatrix}
\ \ 
\text{y} \ \
P^{-1} = \begin{bmatrix} 1/2 & 1/2 \\ 1/2 & -1/2\end{bmatrix},
$$

$$
A = \begin{bmatrix} 1 & 1 \\ 1 & -1\end{bmatrix} \begin{bmatrix} 1 & 0 \\ 0 & -1\end{bmatrix} \begin{bmatrix} 1/2 & 1/2 \\ 1/2 & -1/2\end{bmatrix}.
$$ 





# Ejercicio 1: Cifrado de un Mensaje

Codifica la siguiente frase utilizando el método descrito anteriormente usando la matriz de codificación 

$$A=\begin{bmatrix} 4 & -4 &3\\ 2 & -5&6\\2&-10&11 \end{bmatrix}$$
"LA NARANJA MECANICA"

### Pasos a seguir
a. **Convierte las letras a valores numéricos** siguiendo la tabla anterior.  

b. **Agrupa los valores en vectores columna de $2 \times 1$**.  

c. **Multiplica cada vector por la matriz $A$ para obtener el mensaje cifrado**. 


## Ejercicio 2: Descifrado de un Mensaje con la Matriz Inversa



Descifra el siguiente mensaje codificado utilizando la matriz inversa del código de codificación proporcionado:

$$
\{  84, 93, 148, 40, 83, 138, -16, -65, -160, 61, 113, 203, 130, 143, 228, 13, 47, 67 \},
$$ 

si la matriz de codificación  es la misma del ejercicio anterior.

### Pasos a seguir

a. **Calcula la matriz inversa $A^{-1}$** de la matriz de
codificación proporcionada.
b. **Agrupa los números del mensaje codificado en vectores columna de $3 \times 1$**.  
c. **Multiplica cada vector codificado por la matriz inversa $A^{-1}$ para obtener los vectores originales**.  
d. **Convierte los valores numéricos obtenidos de vuelta a letras** siguiendo la tabla inicial para recuperar el mensaje original.

## Ejercicio 3
Un experto en matemáticas observo el siguiente vector el cual tiene un mensaje encriptado, el cual se sabe que fue encriptado con la técnica anterior. 

el encontró que la matriz llave tiene dos valores propios, uno con multiplicada algebraica 2 y el cual tenia asociado los vectores propios, así
para 
$$\lambda_1 = 3$$

los vectores propios asociados eran

$$
v_1 = \begin{bmatrix} 1 \\ 2\\ 2\end{bmatrix}\ \ \text{y}\ \
v_2 = \begin{bmatrix} 1 \\ 2 \\ 3\end{bmatrix}
$$

Ademas noto que cuando tenia la la combinación espacio de letras "AAA" al convertirlo a vectores y multiplicarlo por la matriz llave, obtenía el mismo vector, es decir tenia la misma combinación de letras.


Descifre el siguiente mensaje encriptado.


 $$\{ -10, 5, -10, -12, 6, -43, -7, -43, -63, 9, -46, 2, -46, -24, -6 \}$$

### Pasos a seguir
a. **Reconstruye la matriz de codificación $A$** utilizando la información de los valores y vectores propios proporcionados.
b. **Calcula la matriz inversa $A^{-1}$** de la matriz de codificación reconstruida.
c. **Agrupa los números del mensaje codificado en vectores columna de $3 \times 1$**.  
d. **Multiplica cada vector codificado por la matriz inversa $A^{-1}$ para obtener los vectores originales**.  
e. **Convierte los valores numéricos obtenidos de vuelta a letras** siguiendo la tabla inicial para recuperar el mensaje original.


In [27]:
import numpy as np

# Diccionario para letra a código
def letra_a_codigo(char):
    if char == ' ':
        return 0
    else:
        return ord(char.upper()) - ord('A') + 1

#frase = 'LA NARANJA MECANICA' # punto 1
#frase= 'MALDITOS BASTARDOS' # punto 2
frase='LA MILLA VERDE'
# Paso a: Conversión a códigos numéricos
codigos = [letra_a_codigo(c) for c in frase]

    # Paso b: Agrupamiento en vectores de 3
vectores = [codigos[i:i+3] for i in range(0, len(codigos), 3)]

    # Completar el último vector con ceros si no tiene 3 elementos
if len(vectores[-1]) < 3:
    vectores[-1] = vectores[-1] + [0] * (3 - len(vectores[-1]))

print("Vectores agrupados de 3:", vectores)

# Convertir la lista de vectores en una matriz donde cada columna es un vector
matriz_vectores = np.array(vectores).T

print("\nMatriz de vectores (3 x número de vectores):")
print(matriz_vectores)
print(f"\nDimensiones: {matriz_vectores.shape[0]} filas x {matriz_vectores.shape[1]} columnas")

Vectores agrupados de 3: [[12, 1, 0], [13, 9, 12], [12, 1, 0], [22, 5, 18], [4, 5, 0]]

Matriz de vectores (3 x número de vectores):
[[12 13 12 22  4]
 [ 1  9  1  5  5]
 [ 0 12  0 18  0]]

Dimensiones: 3 filas x 5 columnas


In [28]:
#A=np.diag([3,2,5]) ##Punto 1 y 2
A=np.diag([1,3,3]) ##Punto 3
# Buscar una matriz P con coeficientes enteros cuya inversa también tenga coeficientes enteros
# Una opción es usar una matriz con determinante ±1
P = np.array([[1, 1, 1], [1, 2, 2], [1, 2, 3]])
P_inv = np.linalg.inv(P)
print("Matriz P:")
print(P)
print("\nMatriz P inversa:")
print(P_inv)
C=P @ A @ P_inv
print("\nMatriz de codificación C:")
print(C)


Matriz P:
[[1 1 1]
 [1 2 2]
 [1 2 3]]

Matriz P inversa:
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]

Matriz de codificación C:
[[-1.  2.  0.]
 [-4.  5.  0.]
 [-4.  2.  3.]]


In [29]:
## Matriz codificada
matriz_codificada = C @ matriz_vectores
print("\nMatriz codificada (C * matriz_vectores):")
print(matriz_codificada)    


Matriz codificada (C * matriz_vectores):
[[-10.   5. -10. -12.   6.]
 [-43.  -7. -43. -63.   9.]
 [-46.   2. -46. -24.  -6.]]
